#server:
#  port: 9090
#  servlet:
#    context-path: /
#    
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springweb?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
#    username: root
#    password: root
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
#    
#    
#mybatis:
#  config-location: classpath:/spring/MybatisConfig.xml
#  
